apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: neighbouring-galliform-nodejs
  janus-idp.io/tekton: neighbouring-galliform-nodejs
  backstage.io/kubernetes-id: neighbouring-galliform-nodejs
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: neighbouring-galliform-nodejs
resources: 
- deployment.yaml
- route.yaml
- service.yaml
