apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: neighbouring-galliform-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: neighbouring-galliform-nodejs 
  name: neighbouring-galliform-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: neighbouring-galliform-nodejs 
